version: '3.8'

networks:
  mm-network:
services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgres
    networks:
      - mm-network
  mm-service:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mm-network