# Конфигурация сервера
server:
  tls-cert: ""                   # Путь к TLS сертификату для HTTPS (если не используется HTTPS, оставить пустым)
  key-file: ""                   # Путь к ключевому файлу для TLS (если не используется HTTPS, оставить пустым)
  host: "127.0.0.1"              # Хост сервера, на котором будет работать приложение
  port: "8080"                   # Порт, на котором сервер будет слушать запросы

# Конфигурация матчмейкера
matchmaker:
  group-size: 3                  # Размер группы игроков, которые будут помещены в матч
  acceptable-waiting-time: 30s   # Максимально допустимое время ожидания игроков в очереди
  delta-latency: 50.0            # Допустимая разница в латентности (в миллисекундах) между игроками
  delta-skill: 10.0              # Допустимая разница в уровне навыков между игроками
