name: CI Pipeline for Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-alior-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
      - name: Сборка проекта
        run: go build -o /dev/null ./...
