name: CI Pipeline for Main Branch

on:
  push:
    branches:
      - main

jobs:
  check-code:
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SECRET }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Установка reviewdog
        run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest
      - name: Запуск golangci-lint через Reviewdog
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
          echo "Install done"
          golangci-lint run --out-format=line-number --disable typecheck | reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-review -fail-on-error=true
  build:
    runs-on: ubuntu-latest
    needs:
      - check-code
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Проверка версии Go
        run: go version
      - name: Установка кэша зависимостей
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Установка зависимостей
        run: go mod tidy
      - name: Сборка проекта
        run: go build -o /dev/null ./...
  check-unit-tests:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0
      - name: Проверка зависимостей
        run: go mod verify
      - name: Сборка
        run: go build -v ./...
      - name: Запуск go vet
        run: go vet ./...
      - name: Установка staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Запуск staticcheck
        run: staticcheck ./...
      - name: Установка golint
        run: go install golang.org/x/lint/golint@latest
      - name: Запуск golint
        run: golint ./...
      - name: Запуск тестов
        run: go test -race -vet=off ./...
